# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bcrypt'
gem 'mini_magick'
gem 'open-uri'
gem 'pry'
gem 'rack-test'
gem 'require_all'
gem 'rspec'
gem 'securerandom'
gem 'sinatra'
gem 'sqlite3'
gem 'thin'
